# These are supported funding model platforms

github: fire1ce
patreon: fire1ce
custom: ["https://www.paypal.com/donate/?hosted_button_id=Y5NSXQQ6VPSK6&Z3JncnB0=", "https://www.buymeacoffee.com/fire1ce/"]
