# Project information
site_name: 3os
site_url: https://3os.org
site_author: Stas Yakobov
site_description: >-
  Collocation of technical documentation and guides for devops, developers, pentesters, systems administrators and other IT professionals.
repo_url: https://github.com/fire1ce/3os.org
repo_name: fire1ce/3os.org
edit_uri: edit/main/docs/

# Theme Configuration
theme:
  name: material
  highlightjs: true
  custom_dir: theme
  language: en
  features:
    - navigation.tabs
    # - navigation.instant
    - navigation.top
    - navigation.indexes
    - navigation.tracking
    - navigation.sections
    - search.suggest
    - search.highlight
    - search.share

  palette:
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: teal
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: teal
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font: false
  icon:
    logo: material/chart-donut-variant
  favicon: assets/favicon.png
# Custom theme additions
extra_css:
  - css/fonts.css
  - css/extra.css

# Plugins
plugins:
  - search:
      prebuild_index: true
      lang: 'en'
  - exclude-search:
      exclude:
        - blog.md
  - awesome-pages
  - tags:
      tags_file: tags.md
  - meta-descriptions
  - external-markdown
  - minify:
      minify_html: true
      htmlmin_opts:
          remove_comments: true
  - ezlinks
  - redirects:
      redirect_maps:
          'guides/openwrt/tipsandtricks.md' : 'infrastructure/openwrt/tipsandtricks.md'
          'guides/proxmox/igpu-passthrough-to-vm.md' : 'infrastructure/proxmox/igpu-passthrough-to-vm.md'
          'guides/proxmox/networking.md' : 'infrastructure/proxmox/networking.md'
          'guides/proxmox/pgu-passthrough-to-vm.md': 'infrastructure/proxmox/pgu-passthrough-to-vm.md'
          'guides/proxmox/tipsandtricks.md': 'infrastructure/proxmox/tipsandtricks.md'
          'guides/synology/allow-ssh-with-rsa-key.md' : 'infrastructure/synology/allow-ssh-with-rsa-key.md'
          'guides/synology/auto-dsm-config-backup.md' : 'infrastructure/synology/auto-dsm-config-backup.md'
          'guides/synology/disable-dms-listening-on-80-443-ports.md' : 'infrastructure/synology/disable-dms-listening-on-80-443-ports.md'
          'guides/synology/Install-oh-my-zsh.md' : 'infrastructure/synology/Install-oh-my-zsh.md'
          'guides/synology/Installing-vm-tools-on-virtual-machine.md' : 'infrastructure/synology/Installing-vm-tools-on-virtual-machine.md'
          'guides/ubiquiti/edge-router.md' : 'infrastructure/ubiquiti/edge-router.md'
          'guides/ubiquiti/udm-pro.md' : 'infrastructure/ubiquiti/udm-pro.md'
          'penetration-testing/other/vmware-fusion.md' : 'infrastructure/vmware/vmware-fusion.md'


extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/fire1ce
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/stas-yakobov
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/3os.org

# Extensions
markdown_extensions:
  - admonition
  - sane_lists
  - attr_list
  - markdown.extensions.codehilite:
      guess_lang: false
  - def_list
  - footnotes
  - abbr
  - meta
  - md_in_html
  - tables
  - toc:
      title: On This Page
      permalink: true
      toc_depth: '3'
      separator: '-'
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.extra
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      linenums_style: pymdownx-inline
  - pymdownx.inlinehilite
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: fire1ec
      repo: 3os.org
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - pymdownx.tilde
  - meta
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

# Copyright
copyright: 'Copyright &copy; 3os.org 2022'
