name: Check Links
on:
  workflow_dispatch:
    branches:
    - gh-pages
  schedule:
    - cron: '0 4 * * *'




jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Link Checker
        uses: lycheeverse/lychee-action@v1.3.1
        with:
          fail: true
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}



