name: Link Snitch

on:
  push:
    branches:
      - main

env:
  URL: https://3os.org
  # FILENAME: report.yaml
  # CONFIG: config.json

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Check out main
        uses: actions/checkout@main
        with:
          fetch-depth: 20
      - name: Report broken links
        uses: victoriadrake/link-snitch@master