name: Check Links
on:
  workflow_dispatch:
    branches:
      - gh-pages
  push:
    branches:
      - main
      - gh-pages

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      
      - uses: peaceiris/actions-gh-pages@v3
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v1.3.1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      # - name: Create Issue From File
      #   if: ${{ steps.lychee.outputs.exit_code != 0 }}
      #   uses: peter-evans/create-issue-from-file@v3
      #   with:
      #     title: Link Checker Report
      #     content-filepath: ./lychee/out.md
      #     labels: report, automated issue



