
name: CI
# Controls when the workflow will run
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:
  
jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v3

      
      # Deploy MkDocs
      - name: Deploy MkDocs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CUSTOM_DOMAIN: 3os.org
          CONFIG_FILE: ./mkdocs.yml
          EXTRA_PACKAGES: build-base
          # GITHUB_DOMAIN: github.myenterprise.com
          REQUIREMENTS: ./requirements.txt

      - name: Wait for deploy to succeed
        uses: fountainhead/action-wait-for-check@v1.0.0
        id: wait-for-deploy
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: deploy
          ref: ${{ github.event.pull_request.head.sha || github.sha }}

      - name: Clear Cloudflare cache with a passing deploy
        if: steps.wait-for-build.outputs.conclusion == 'success'
        uses: Cyb3r-Jak3/action-cloudflare-cache@main
        with:
          # Zone is required by both methods
          zone: ${{ secrets.CLOUDFLARE_ZONE }}
          # Using API Token
          api_token: ${{ secrets.CLOUDFLARE_TOKEN }}




