
name: CI
# Controls when the workflow will run
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 4 * * *'

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: byrnereese/github-action-mkdocs-link-check@main
      with:
        use-verbose-mode: 'yes'
        folder-path: 'docs/*'

  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2

      
      # Deploy MkDocs
      - name: Deploy MkDocs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CUSTOM_DOMAIN: 3os.org
          CONFIG_FILE: ./mkdocs.yml
          EXTRA_PACKAGES: build-base
          # GITHUB_DOMAIN: github.myenterprise.com
          REQUIREMENTS: ./requirements.txt

      # Clear Cloudfalre cache
      - name: Clear Cloudflare cache
        uses: Cyb3r-Jak3/action-cloudflare-cache@main
        with:
          # Zone is required by both methods
          zone: ${{ secrets.CLOUDFLARE_ZONE }}
          # Using API Token
          api_token: ${{ secrets.CLOUDFLARE_TOKEN }}



