name: cloudflare-cache

on:
  workflow_run:
    workflows: [pages-build-deployment, deploy, 'github-pages[bot]']
    types: [completed]

jobs:
  cloudflare-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Clear Cloudflare cache with a passing deploy
        if: steps.wait-for-deploy.outputs.conclusion == 'success'
        uses: Cyb3r-Jak3/action-cloudflare-cache@main
        with:
          # Zone is required by both methods
          zone: ${{ secrets.CLOUDFLARE_ZONE }}
          # Using API Token
          api_token: ${{ secrets.CLOUDFLARE_TOKEN }}