name: cloudflare-clear-cache

on:
  workflow_run:
    workflows: [pages-build-deployment]
    types: [completed]

jobs:
  cloudflare-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Clear Cloudflare Cache
        uses: Cyb3r-Jak3/action-cloudflare-cache@main
        with:
          zone: ${{ secrets.CLOUDFLARE_ZONE }}
          api_token: ${{ secrets.CLOUDFLARE_TOKEN }}